import Head from "next/head";
import axios from "axios";
import { useRouter } from "next/router";

const Home = ({ user }) => {
  const router = useRouter();

  const logout = () => {
    axios
      .post("/api/auth/logout")
      .then((res) => {
        router.push("/login");
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <div>
      <Head>
        <title>Job Tracker</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {user.id}
      {user.email}
      <a onClick={logout}>Logout</a>
    </div>
  );
};

export default Home;

export const getServerSideProps = async (ctx) => {
  const token = ctx.req.cookies["auth-token"];

  if (!token) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  try {
    const { data } = await axios.get(`${process.env.API}/auth/check`, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    return {
      props: {
        user: {
          id: data.id,
          email: data.username,
        },
      },
    };
  } catch (err) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
};
